### ISSUE TITLE
Make a GitHub template repo

### ISSUE THREAD

**Issue by pete-murphy** [purescript-templates/react-basic-hooks#4]
Any thoughts on converting this to a [GitHub template repo](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/creating-a-template-repository)? It seems like it would achieve about the same thing as `git clone --depth 1` but might be slightly more ergonomic from a user's perspective. Also, I think if someone creates a repo from a template repo, the initial commit is attributed to that user rather than the template owner.

**Comment by milesfrain** [comment]
That sounds good. Will give this a shot and see if it affects the clone command. The [docs only describe differences when forking](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template).

**Comment by milesfrain** [comment]
Looks like that only adds the "Use this Template" button in the web UI to create a repo tracked in GH. Folks who just want to mess around with the template locally (without creating another GH repo) can still run the same `git clone --depth 1` command.
